import { Header } from '@/components/Header'
import { UserProvider, VideoProvider } from '@/contexts'

import '@/styles/global.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR" className={inter.className}>
      <body>
        <UserProvider>
          <VideoProvider>
            <Header />
            <main className="pt-24 px-6 pb-6">{children}</main>
          </VideoProvider>
        </UserProvider>
      </body>
    </html>
  )
}
